=== hmrc/vat-api/public/api/conf/1.0/schemas/VatReturnDeclaration.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "VAT Return Declaration",
  "description": "VAT Return Declaration",
  "type": "object",
  "properties": {
    "periodKey": {
      "description": "The ID code for the period that this obligation belongs to. The format is a string of four alphanumeric characters. Occasionally the format includes the # symbol.",
      "type": "string",
      "minLength": 4,
      "maxLength": 4,
      "example": "18AD, 18A1, #001"
    },
    "vatDueSales": {
      "description": "VAT due on sales and other outputs. This corresponds to box 1 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "vatDueAcquisitions": {
      "description": "VAT due in the period on acquisitions of goods made in Northern Ireland from EU Member States. This corresponds to box 2 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "totalVatDue": {
      "description": "Total VAT due (the sum of vatDueSales and vatDueAcquisitions). This corresponds to box 3 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "vatReclaimedCurrPeriod": {
      "description": "VAT reclaimed in the period on purchases and other inputs (including acquisitions in Northern Ireland from EU member states). This corresponds to box 4 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "netVatDue": {
      "description": "The difference between totalVatDue and vatReclaimedCurrPeriod. This corresponds to box 5 on the VAT Return form. The value must be between 0.00 and 99999999999.99",
      "$ref": "#/definitions/monetaryPos11"
    },
    "totalValueSalesExVAT": {
      "description": "Total value of sales and all other outputs excluding any VAT. This corresponds to box 6 on the VAT Return form. The value must be in pounds (no pence) between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "totalValuePurchasesExVAT": {
      "description": "Total value of purchases and all other inputs excluding any VAT (including exempt purchases). This corresponds to box 7 on the VAT Return form. The value must be in pounds (no pence) between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "totalValueGoodsSuppliedExVAT": {
      "description": "Total value of dispatches of goods and related costs (excluding VAT) from Northern Ireland to EU Member States. This corresponds to box 8 on the VAT Return form. The value must be in pounds (no pence) between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "totalAcquisitionsExVAT": {
      "description": "Total value of acquisitions of goods and related costs (excluding VAT) made in Northern Ireland from EU Member States. This corresponds to box 9 on the VAT Return form. The value must be in pounds (no pence) between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "finalised": {
      "description": "Declaration that the user has finalised their VAT return.",
      "type": "boolean",
      "example": "true"
    }
  },
  "required": [
    "periodKey",
    "vatDueSales",
    "vatDueAcquisitions",
    "totalVatDue",
    "vatReclaimedCurrPeriod",
    "netVatDue",
    "totalValueSalesExVAT",
    "totalValuePurchasesExVAT",
    "totalValueGoodsSuppliedExVAT",
    "totalAcquisitionsExVAT",
    "finalised"
  ],
  "definitions": {
    "monetaryPos11": {
      "description": "Defines a monetary value (to 2 decimal places), between 0 and 99,999,999,999.99",
      "type": "number",
      "minimum": 0.0,
      "maximum": 99999999999.99,
      "multipleOf": 0.01
    },
    "monetaryPosNeg13": {
      "description": "Defines a monetary value (to 2 decimal places), between -9,999,999,999,999.99 and 9,999,999,999,999.99",
      "type": "number",
      "minimum": -9999999999999.99,
      "maximum": 9999999999999.99,
      "multipleOf": 0.01
    },
    "monetaryPosNegZeroDec13": {
      "description": "Defines a monetary value (to 2 zeroed decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
      "type": "number",
      "minimum": -9999999999999.00,
      "maximum": 9999999999999.00
    }
  },
  "additionalProperties": false
}

=== hmrc/vat-api/public/api/conf/1.0/examples/SubmitVatReturnHash.json
{
  "periodKey": "#001",
  "vatDueSales": 100.00,
  "vatDueAcquisitions": 100.00,
  "totalVatDue": 200.00,
  "vatReclaimedCurrPeriod": 100.00,
  "netVatDue": 100.00,
  "totalValueSalesExVAT": 500,
  "totalValuePurchasesExVAT": 500,
  "totalValueGoodsSuppliedExVAT": 500,
  "totalAcquisitionsExVAT": 500,
  "finalised": true
}

=== hmrc/vat-api/public/api/conf/1.0/examples/VatReturnDeclaration.json
{
  "periodKey": "#001",
  "vatDueSales": 100.00,
  "vatDueAcquisitions": 100.00,
  "totalVatDue": 200,
  "vatReclaimedCurrPeriod": 100.00,
  "netVatDue": 100,
  "totalValueSalesExVAT": 500,
  "totalValuePurchasesExVAT": 500,
  "totalValueGoodsSuppliedExVAT": 500,
  "totalAcquisitionsExVAT": 500,
  "finalised": true
}
